sudo: required
language: C++

services:
        -docker

before_install:
        -docker pull shreyas911/my_docker_image:v1.0
        -export DOCKER_RUN="docker run -v ${TRAVIS_BUILD_DIR}:/home/test/ shreyas911/my_docker_image:v1.0"

script:
        -cd proj02/
        -${DOCKER_RUN} /bin/bash -l -c "module load hdf5 && autoreconf -f -i && ./configure && make && make check"

notifications:
        email: false

