set terminal png

set title "1D Temperature field"
set xlabel "x"
set ylabel "Temperature"

### This range is dependent on L given in input.dat
set xrange [0:1]

### Plot of the temperature field
set output 'plot.png'; plot 'output.log' using 1:3 title 'Computed T vs x' with points, 'output.log' using 1:3 title 'Computed T vs x' with lines, 'output.log' using 1:2 title 'Exact T vs x' with lines


